### ISSUE TITLE
Role not pushed to Galaxy

### ISSUE THREAD

**Issue by perimore** [arista-eosplus/ansible-eos-bgp#5]
Hi,

This role doesn't seem to have been pushed to Galaxy as I seem to be using the old module:

TASK [arista.eos-bgp : configure BGP global parameters] ************************
task path: /private/etc/ansible/roles/arista.eos-bgp/tasks/main.yaml:2
<spine1> ESTABLISH LOCAL CONNECTION FOR USER: sean
<spine1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461741237.67-249258983832970 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461741237.67-249258983832970 `" )'
<spine1> PUT /var/folders/3q/q76fdfsd043dzhmcjldlqpjr0000gn/T/tmpKO36yu TO /Users/sean/.ansible/tmp/ansible-tmp-1461741237.67-249258983832970/eos_bgp_config
<spine1> EXEC /bin/sh -c 'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /Library/Frameworks/Python.framework/Versions/2.7/bin/python /Users/sean/.ansible/tmp/ansible-tmp-1461741237.67-249258983832970/eos_bgp_config; rm -rf "/Users/sean/.ansible/tmp/ansible-tmp-1461741237.67-249258983832970/" > /dev/null 2>&1'
fatal: [spine1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "eos_bgp_config"}, "module_stderr": "No handlers could be found for logger \"pyeapi.eapilib\"\nTraceback (most recent call last):\n  File \"/var/folders/3q/q76fdfsd043dzhmcjldlqpjr0000gn/T/ansible_Fg9Hw4/ansible_module_eos_bgp_config.py\", line 598, in <module>\n    main()\n  File \"/var/folders/3q/q76fdfsd043dzhmcjldlqpjr0000gn/T/ansible_Fg9Hw4/ansible_module_eos_bgp_config.py\", line 593, in main\n    supports_check_mode=True)\n  File \"/var/folders/3q/q76fdfsd043dzhmcjldlqpjr0000gn/T/ansible_Fg9Hw4/ansible_module_eos_bgp_config.py\", line 245, in __init__\n    self._node.connect()\n  File \"/var/folders/3q/q76fdfsd043dzhmcjldlqpjr0000gn/T/ansible_Fg9Hw4/ansible_module_eos_bgp_config.py\", line 180, in connect\n    raise ValueError('unable to connect to {}'.format(node))\nValueError: unable to connect to Node(connection=EapiConnection(transport=unix:/var/run/command-api.sock))\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

**Comment by grybak-arista** [comment]
Updated role pushed to Galaxy
